name: Bundle and Deploy

on:
  push:
    branches:
      - "[0-9]+.[0-9]+/*"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bundle-deploy:
    name: Bundle and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v7
      - name: Setup Deno Environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Dependencies
        run: deno install
      - name: Bundle Extensions
        run: deno task bundle
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: bundles
          destination_dir: ${{ github.ref_name }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
